document.write("   <div class = 'aboutMe'> ")
document.write("     <h2> About </h2> ")
document.write("    <img id = 'me' class = 'me2' src = 'https://scontent-sea1-1.xx.fbcdn.net/hphotos-xfa1/v/t1.0-9/150228_454557259079_6459306_n.jpg?oh=cab0a6bea54110d85fab070d4b3cbb13&oe=56AF5FF4' height = '200px', width = '200px'> ")
document.write(" <p>My Name Is Alex</p> ")
document.write(" <p>I'm Living In Portland</p> ")
document.write(" <p>Switching Careers</p>  ")
document.write("<p>Learning To Code</p>  ")
document.write(" <p>And Writing About It</p> ")
document.write("    <a id = 'github' href = 'https://github.com/aml630'><img src = 'https://assets-cdn.github.com/images/modules/logos_page/GitHub-Mark.png', height = '100px'></a>  ")
document.write("    <a id = 'github' href = 'https://twitter.com/alars630'><img src = 'https://cdn3.iconfinder.com/data/icons/social-media-chat-1/512/Twitter-128.png', height = '80px'></a>  ")
document.write("   </div> ")
document.write("   <div class = 'recentPosts'> ")
document.write("  <h2>Recent Posts </h2> ")
document.write("   <li><img class = 'recentPostsImg' src = 'http://longfengdazhan.com/wp-content/uploads/2014/11/%E7%BA%A2%E8%8D%AF%E4%B8%B8.jpg' height = '40px' width= '60px'><a href = 'Post1.html'>Going Rogue</a></li> ")
document.write("  </div> ")
document.write("  <a class='twitter-timeline' href='https://twitter.com/alars630' data-widget-id='666721907039825920'>Tweets by @alars630</a> ")
document.write("  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)) ")
document.write("  {js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','twitter-wjs');</script> ")
